export const GET_USER_LIST = "GET_USER_LIST";
export const GET_USER_LIST_PENDING = "GET_USER_LIST_PENDING";
export const GET_USER_LIST_FULFILLED = "GET_USER_LIST_FULFILLED";
export const GET_USER_LIST_REJECTED = "GET_USER_LIST_REJECTED";

export const CREATE_USER = "CREATE_USER";
export const CREATE_USER_PENDING = "CREATE_USER_PENDING";
export const CREATE_USER_FULFILLED = "CREATE_USER_FULFILLED";
export const CREATE_USER_REJECTED = "CREATE_USER_REJECTED";
